version: '3'

services:
  sf-db:
    image: 'mysql:8.0.18'
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - "sf-db:/var/lib/mysql"
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: Sf_name
      MYSQL_USER: Sf_user
      MYSQL_PASSWORD: Sf_password
      MYSQL_ROOT_PASSWORD: Sf_root_password

  php:
    build:
      context: "./php-fpm"
      args:
        UID: ${HOST_USER_ID}
        GUID: ${HOST_GUID_ID}
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
    volumes:
      - "${APP_FOLDER}:/var/www"

  nginx:
    container_name: "nginx"
    build:
      context: "./nginx"
    volumes:
      - ${APP_FOLDER}:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    ports:
      - "80:80"

volumes:
  sf-db: { }
